"""Admission boundary tests: toolrush_admission.readonly() must reject anything
that writes, executes, or escapes the intended read-only set. Run: python repro_admission.py
"""
import os, sys

sys.path.insert(0, r"C:/dev/AppData/Local/hermes/hermes-agent")
os.environ.setdefault("HERMES_HOME", os.path.join(tempfile_dir := __import__('tempfile').gettempdir(), "toolrush-reviewer-home"))

from agent.toolrush_admission import readonly, _stage

PASS = []
def check(name, cmd, expect):
    got = readonly(cmd)
    ok = got == expect
    PASS.append((name, ok))
    print(f"{'PASS' if ok else 'FAIL'}  {name:58s} got={got} want={expect}  :: {cmd!r}")

# --- must be REJECTED (write/exec/escape) ---
check("redirect stdout",        "echo hi > /tmp/f", False)
check("redirect append",        "cat a >> b", False)
check("redirect stdin-from",    "grep x < /etc/passwd", False)
check("fd redirect",            "ls 2>&1", False)
check("heredoc",                "cat <<EOF", False)
check("backtick substitution",  "echo `id`", False)
check("cmd substitution",       "echo $(id)", False)
check("param expansion !",      "echo ${!x}", False)
check("param expansion =",      "echo ${x:=y}", False)
check("background &",           "sleep 5 &", False)
check("double &&",              "ls && rm x", False)
check("pipe to tee (write)",    "ls | tee /tmp/f", False)
check("pipe to sh",             "echo id | sh", False)
check("brace group",            "{ echo hi; }", False)
check("subshell",               "(ls)", False)
check("unknown binary",         "some_random_binary --flag", False)
check("python script exec",     "python script.py", False)
check("python -c",              "python -c 'print(1)'", False)
check("node eval",              "node -e '1'", False)
check("npm run",                "npm run build", False)
check("pip install",            "pip install requests", False)
check("uv run",                 "uv run x.py", False)
check("curl -o write",          "curl -o /tmp/f http://x.com", False)
check("curl -T upload",         "curl -T f http://x.com", False)
check("curl -X POST",           "curl -X POST http://x.com", False)
check("curl config file",       "curl -K cfg http://x.com", False)
check("sed write via w",        "sed -n '1p' a", True)   # allowed numeric print
check("sed script flag",        "sed -e 's/a/b/' f", False)
check("sed inplace",            "sed -i 's/a/b/' f", False)
check("git config write",       "git config user.email a@b.c", False)
check("git push",               "git push", False)
check("git checkout",           "git checkout main", False)
check("git commit",             "git commit -m x", False)
check("git clean",              "git clean -fd", False)
check("git -C traversal ok?",   "git -C . status", True)
check("git ext-diff",           "git diff --ext-diff", False)
check("git textconv",           "git log --textconv", False)
check("git exec path",          "git --exec-path", False)
check("git output file",        "git status --output x", False)
check("git show writes?",       "git show --output=x", False)
check("git cmd injection",      'git log --output=$HOME/x', False)
check("git backtick",           "git log `boom`", False)
check("rg pre-gate exec",       "rg --pre ./evil pat", False)
check("rg hostname-bin exec",   "rg --hostname-bin ./evil pat", False)
check("sort write out",         "sort -o /tmp/f f", False)
check("sort compress exec",     "sort --compress-program=gzip f", False)
check("sort tmpdir write",      "sort -T /tmp f", False)
check("uniq 2-operand write",   "uniq in out", False)
check("jq library exec",        "jq -L ./x '.' f", False)
check("jq run-tests",           "jq --run-tests f", False)
check("xargs would be blocked", "xargs echo", False)
check("find exec",              "find . -name x", False)
check("awk exec",               "awk '{print}' f", False)
check("chmod",                  "chmod +x f", False)
check("mkdir",                  "mkdir d", False)
check("rm",                     "rm f", False)
check("shell var assignment",   "FOO=bar ls", False)
check("assignment-only",        "FOO=bar", False)
check("newline multi-cmd",      "ls\nrm f", False)
check("glob-into-command",      "echo *", True)  # echo * is read-only (prints names)
check("tilde in arg",           "ls ~", True)
check("env wrapper",            "env ls", False)
check("nohup",                  "nohup ls", False)
check("timeout wrapper",        "timeout 5 ls", False)
check("printf -v var",          "printf -v x foo", False)

# --- must be ACCEPTED (legit read-only) ---
check("cat",                    "cat README.md", True)
check("grep",                   "grep -n foo bar.txt", True)
check("ls",                     "ls -la", True)
check("rg plain",               "rg pattern .", True)
check("rg with glob",           "rg pat --glob '*.py'", True)
check("git status",             "git status", True)
check("git log",                "git log --oneline -5", True)
check("git diff",               "git diff HEAD~1", True)
check("git branch -a",          "git branch -a", True)
check("git config --get",       "git config --get user.email", True)
check("git ls-files",           "git ls-files", True)
check("curl get",               "curl -sS https://example.com", True)
check("curl -I",                "curl -I https://example.com", True)
check("curl flags cluster",     "curl -sSfL https://example.com", True)
check("curl -m -H",             "curl -m 5 -H 'Accept: x' https://example.com", True)
check("sed numeric print",      "sed -n '10,20p' file.txt", True)
check("sort plain",             "sort f.txt", True)
check("uniq -c",                "uniq -c f.txt", True)
check("jq filter",              "jq '.' data.json", True)
check("date",                   "date +%s", True)
check("hostname",               "hostname", True)
check("wc",                     "wc -l f.txt", True)
check("ps",                     "ps aux", True)
check("md5sum",                 "md5sum f.txt", True)
check("pipeline of reads",      "cat f | sort | uniq -c", True)
check("chained && reads",       "ls && cat f", True)
check("git pipe wc",            "git log | wc -l", True)
check("printf",                 "printf '%s\\n' hi", True)

print(f"\nTOTAL {sum(1 for _, ok in PASS if ok)}/{len(PASS)} passed")
fails = [n for n, ok in PASS if not ok]
if fails:
    print("FAILURES:", ", ".join(fails))
